name: "MQTT Bridge for Bresser Weatherstation"
version: "0.1.6.1"
slug: "weatherstation"
description: "Empfängt mittels Webserver Wetterdaten einer Bresser Wetterstation und veröffentlicht sie via MQTT"
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
host_network: true
options:
  MQTT_HOST: "localhost"
  MQTT_PORT: 1883
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  MQTT_TOPIC: "weatherstation/data"
schema:
  MQTT_HOST: str
  MQTT_PORT: int
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_TOPIC: str
