name: "MQTT Bridge for Bresser Weatherstation"
version: "0.1.7.3"
slug: "weatherstation"
description: "Empfängt mittels Webserver Wetterdaten einer Bresser Wetterstation und veröffentlicht sie via MQTT"
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
host_network: true
options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: ha_mqtt
  mqtt_password: ha_mqtt
  mqtt_topic: wetterstation/data
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
